coverage:
  status:
    project:
      default:
        target: auto
        base: pr
      falcon-client:
        paths:
          - falcon-client/
      falcon-server:
        paths:
          - falcon-server/
      falcon-server-env:
        paths:
          - falcon-server-env/
      falcon-magento2-api:
        paths:
          - falcon-magento2-api/
      falcon-wordpress-api:
        paths:
          - falcon-wordpress-api/

comment: off
